#!/usr/bin/env bash
# Creates backend/.env.production with generated secrets.
# Prompts only for values you must supply from Neon and Upstash.
#
# Usage: ./backend/scripts/init-env-production.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="${ROOT}/.env.production"
EXAMPLE="${ROOT}/.env.production.example"

if [[ -f "$ENV_FILE" ]]; then
  echo "backend/.env.production already exists."
  read -r -p "Overwrite? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || exit 0
fi

JWT_SECRET="$(openssl rand -base64 32)"
COOKIE_SECRET="$(openssl rand -base64 32)"
MFA_KEY="$(openssl rand -base64 32)"

echo ""
echo "Paste your Neon Medusa DATABASE_URL"
echo "(Neon dashboard → your 'medusa' database → connection string)"
read -r -p "> " DATABASE_URL

echo ""
echo "Paste your Upstash REDIS_URL"
echo "(Upstash dashboard → Redis → TCP → rediss:// URL — NOT the REST URL)"
read -r -p "> " REDIS_URL

if [[ -z "$DATABASE_URL" || -z "$REDIS_URL" ]]; then
  echo "ERROR: DATABASE_URL and REDIS_URL are required." >&2
  exit 1
fi

cat > "$ENV_FILE" <<EOF
# Production Medusa backend — generated by init-env-production.sh
# Used by deploy-railway.sh

NODE_ENV=production

DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}

JWT_SECRET=${JWT_SECRET}
COOKIE_SECRET=${COOKIE_SECRET}
AUTH_MFA_ENCRYPTION_KEY=${MFA_KEY}

STOREFRONT_URL=https://miyako-psi.vercel.app
STORE_CORS=http://localhost:3003,https://miyako-psi.vercel.app
AUTH_CORS=http://localhost:3003,https://miyako-psi.vercel.app

MEDUSA_ADMIN_EMAIL=admin@miyako.art
# Intentionally empty — production-setup.sh auto-generates a secure password and prints it
MEDUSA_ADMIN_PASSWORD=

STRIPE_API_KEY=
STRIPE_WEBHOOK_SECRET=
EOF

chmod 600 "$ENV_FILE" 2>/dev/null || true

echo ""
bash "${ROOT}/scripts/validate-env-production.sh" "$ENV_FILE"
echo ""
echo "Created: backend/.env.production"
echo "Next: ./backend/scripts/deploy-railway.sh"
